// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtiqfsBW1N81r5cLDRpvD8kpRawBMsZAo',
    appId: '1:408958424784:web:48feae43572f24fcb430d5',
    messagingSenderId: '408958424784',
    projectId: 'smart-laundry-b8326',
    authDomain: 'smart-laundry-b8326.firebaseapp.com',
    storageBucket: 'smart-laundry-b8326.firebasestorage.app',
    measurementId: 'G-S7VG4M034F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy-rkEudqa6vsjWw4KEFKG2L9ShyaRWGo',
    appId: '1:408958424784:android:13588435a5b7601db430d5',
    messagingSenderId: '408958424784',
    projectId: 'smart-laundry-b8326',
    storageBucket: 'smart-laundry-b8326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEsmBWaL9VJjYJAgNG6lPIwc1cS4cWq-g',
    appId: '1:408958424784:ios:3e3f1cba944283a6b430d5',
    messagingSenderId: '408958424784',
    projectId: 'smart-laundry-b8326',
    storageBucket: 'smart-laundry-b8326.firebasestorage.app',
    iosBundleId: 'com.example.smartLaundary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEsmBWaL9VJjYJAgNG6lPIwc1cS4cWq-g',
    appId: '1:408958424784:ios:3e3f1cba944283a6b430d5',
    messagingSenderId: '408958424784',
    projectId: 'smart-laundry-b8326',
    storageBucket: 'smart-laundry-b8326.firebasestorage.app',
    iosBundleId: 'com.example.smartLaundary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtiqfsBW1N81r5cLDRpvD8kpRawBMsZAo',
    appId: '1:408958424784:web:d132dcf07e800271b430d5',
    messagingSenderId: '408958424784',
    projectId: 'smart-laundry-b8326',
    authDomain: 'smart-laundry-b8326.firebaseapp.com',
    storageBucket: 'smart-laundry-b8326.firebasestorage.app',
    measurementId: 'G-X8KQ86L5MS',
  );
}
